export const languages = [
  ["Afrikaans", "af-ZA"],
  ["Arabic", "ar-001"],
  ["Bulgarian", "bg-BG"],
  ["Chinese (Simp.)", "cmn-Hans-CN"],
  ["Croatian", "hr_HR"],
  ["Czech", "cs-CZ"],
  ["English", "en-GB"],
  ["French", "fr-FR"],
  ["German", "de-DE"],
  ["Greek", "el-GR"],
  ["Finnish", "fi-FI"],
  ["Hebrew", "he-IL"],
  ["Hindi", "hi-IN"],
  ["Hungarian", "hu-HU"],
  ["Indonesian", "id-ID"],
  ["Italian", "it-IT"],
  ["Japanese", "ja-JP"],
  ["Korean", "ko-KR"],
  ["Dutch", "nl-NL"],
  ["Norwegian", "nb-NO"],
  ["Polish", "pl-PL"],
  ["Portuguese", "pt-PT"],
  ["Romanian", "ro-RO"],
  ["Russian", "ru-RU"],
  ["Slovak", "sk-SK"],
  ["Spanish", "es-ES"],
  ["Swedish", "sv-SE"],
  ["Thai", "th-TH"],
  ["Turkish", "tr-TR"],
  ["Ukrainian", "uk-UA"],
  ["Vietnamese", "vi-VN"],
  ["Zulu", "zu-ZA"],
];
