export const languages = [
  ["Czech Republic", "cs-CZ"],
  ["South Africa", "af-ZA"],
  ["Algeria", "ar-DZ"],
  ["Bahrain", "ar-BH"],
  ["Egypt", "ar-EG"],
  ["Israel", "ar-IL"],
  ["Iraq", "ar-IQ"],
  ["Jordan", "ar-JO"],
  ["Kuwait", "ar-KW"],
  ["Lebanon", "ar-LB"],
  ["Morocco", "ar-MA"],
  ["Oman", "ar-OM"],
  ["Palestinian Territory", "ar-PS"],
  ["Qatar", "ar-QA"],
  ["Saudi Arabia", "ar-SA"],
  ["Tunisia", "ar-TN"],
  ["UAE", "ar-AE"],
  ["Spain", "eu-ES"],
  ["Bulgaria", "bg-BG"],
  ["Spain", "ca-ES"],
  ["China (Simp.)", "cmn-Hans-CN"],
  ["Hong Kong SAR (Trad.)", "cmn-Hans-HK"],
  ["Taiwan (Trad.)", "cmn-Hant-TW"],
  ["Hong Kong", "yue-Hant-HK"],
  ["Croatia", "hr_HR"],
  ["Denmark", "da-DK"],
  ["Australia", "en-AU"],
  ["Canada", "en-CA"],
  ["India", "en-IN"],
  ["Ireland", "en-IE"],
  ["New Zealand", "en-NZ"],
  ["Philippines", "en-PH"],
  ["South Africa", "en-ZA"],
  ["United Kingdom", "en-GB"],
  ["United States", "en-US"],
  ["Iran", "fa-IR"],
  ["France", "fr-FR"],
  ["Philippines", "fil-PH"],
  ["Spain", "gl-ES"],
  ["Germany", "de-DE"],
  ["Greece", "el-GR"],
  ["Finland", "fi-FI"],
  ["Israel", "he-IL"],
  ["India", "hi-IN"],
  ["Hungary", "hu-HU"],
  ["Indonesia", "id-ID"],
  ["Iceland", "is-IS"],
  ["Italy", "it-IT"],
  ["Switzerland", "it-CH"],
  ["Japan", "ja-JP"],
  ["Korea", "ko-KR"],
  ["Lithuania", "lt-LT"],
  ["Malaysia", "ms-MY"],
  ["Netherlands", "nl-NL"],
  ["Norway", "nb-NO"],
  ["Poland", "pl-PL"],
  ["Brazil", "pt-BR"],
  ["Portugal", "pt-PT"],
  ["Romania", "ro-RO"],
  ["Russia", "ru-RU"],
  ["Serbia", "sr-RS"],
  ["Slovakia", "sk-SK"],
  ["Slovenia", "sl-SI"],
  ["Argentina", "es-AR"],
  ["Bolivia", "es-BO"],
  ["Chile", "es-CL"],
  ["Colombia", "es-CO"],
  ["Costa Rica", "es-CR"],
  ["Dominican Republic", "es-DO"],
  ["Ecuador", "es-EC"],
  ["El Salvador", "es-SV"],
  ["Guatemala", "es-GT"],
  ["Honduras", "es-HN"],
  ["México", "es-MX"],
  ["Nicaragua", "es-NI"],
  ["Panamá", "es-PA"],
  ["Paraguay", "es-PY"],
  ["Perú", "es-PE"],
  ["Puerto Rico", "es-PR"],
  ["Spain", "es-ES"],
  ["Uruguay", "es-UY"],
  ["United States", "es-US"],
  ["Venezuela", "es-VE"],
  ["Sweden", "sv-SE"],
  ["Thailand", "th-TH"],
  ["Turkey", "tr-TR"],
  ["Ukraine", "uk-UA"],
  ["Viet Nam", "vi-VN"],
  ["South Africa", "zu-ZA"],
];
